"""Initial schema

Revision ID: 3cc8052744f5
Revises: 
Create Date: 2025-10-07 11:25:25.979171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc8052744f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.BigInteger(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('base_health', sa.Integer(), nullable=False),
    sa.Column('base_mana', sa.Integer(), nullable=False),
    sa.Column('current_health', sa.Integer(), nullable=False),
    sa.Column('current_mana', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_telegram_user_id'), 'characters', ['telegram_user_id'], unique=True)
    op.create_table('character_equipment',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('weapon', sa.String(length=100), nullable=True),
    sa.Column('armor', sa.String(length=100), nullable=True),
    sa.Column('helmet', sa.String(length=100), nullable=True),
    sa.Column('boots', sa.String(length=100), nullable=True),
    sa.Column('gloves', sa.String(length=100), nullable=True),
    sa.Column('ring_1', sa.String(length=100), nullable=True),
    sa.Column('ring_2', sa.String(length=100), nullable=True),
    sa.Column('amulet', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('character_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'item_id', name='uq_character_item')
    )
    op.create_index('idx_character_inventory', 'character_inventory', ['character_id'], unique=False)
    op.create_table('character_stats_cache',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('total_health', sa.Integer(), nullable=False),
    sa.Column('total_mana', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('evasion', sa.Integer(), nullable=False),
    sa.Column('energy_shield', sa.Integer(), nullable=False),
    sa.Column('damage_min', sa.Integer(), nullable=False),
    sa.Column('damage_max', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('critical_chance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('critical_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('attack_speed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('equipment_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('combat_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('enemy_id', sa.String(length=100), nullable=False),
    sa.Column('enemy_level', sa.Integer(), nullable=False),
    sa.Column('enemy_current_health', sa.Integer(), nullable=False),
    sa.Column('enemy_max_health', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combat_states')
    op.drop_table('character_stats_cache')
    op.drop_index('idx_character_inventory', table_name='character_inventory')
    op.drop_table('character_inventory')
    op.drop_table('character_equipment')
    op.drop_index(op.f('ix_characters_telegram_user_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
